# Generated by Django 5.1.2 on 2024-11-11 17:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_courses_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Courses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_image_url', models.URLField()),
                ('course_name', models.CharField(max_length=100)),
                ('course_description', models.TextField()),
                ('course_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('course_schedule', models.CharField(max_length=40)),
                ('begins', models.DateField()),
                ('ends', models.DateField()),
                ('course_duration', models.CharField(max_length=30)),
                ('course_category_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.courses_category')),
            ],
        ),
    ]
