# Generated by Django 5.1.2 on 2024-11-11 17:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_people_interested'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cantons',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('canton_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Provinces',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('province_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Districts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('district_name', models.CharField(max_length=100)),
                ('canton_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.cantons')),
            ],
        ),
        migrations.CreateModel(
            name='Neighborhoods',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('neighborhood_name', models.CharField(max_length=100)),
                ('district_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.districts')),
            ],
        ),
        migrations.CreateModel(
            name='Addresses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.TextField()),
                ('neighborhood_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.neighborhoods')),
            ],
        ),
        migrations.AddField(
            model_name='cantons',
            name='province_fk',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.provinces'),
        ),
    ]
