# Generated by Django 5.1.2 on 2024-11-11 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_student_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Identifications',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identification_type', models.CharField(max_length=50)),
            ],
        ),
    ]
