# Generated by Django 5.1.2 on 2024-11-11 19:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_identifications'),
    ]

    operations = [
        migrations.CreateModel(
            name='Form',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identification_number', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(max_length=50)),
                ('first_last_name', models.CharField(max_length=50)),
                ('second_last_name', models.CharField(max_length=50)),
                ('birth_date', models.DateField()),
                ('phone_number', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('address_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.addresses')),
                ('course_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.courses')),
                ('genre_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.genre')),
                ('identification_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.identifications')),
                ('student_status_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.student_status')),
            ],
        ),
    ]
