# Generated by Django 5.1.2 on 2024-11-11 19:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_administrator'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_name', models.CharField(max_length=50)),
                ('student_first_last_name', models.CharField(max_length=50)),
                ('student_second_last_name', models.CharField(max_length=50)),
                ('student_birth_date', models.DateField()),
                ('student_phone_number', models.CharField(max_length=20)),
                ('student_email', models.EmailField(max_length=254)),
                ('student_address_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.addresses')),
                ('student_auth_user_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
