# Generated by Django 5.1.2 on 2024-11-11 19:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_payment_methods'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_date', models.DateTimeField()),
                ('payment_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payment_receipt_url', models.URLField()),
                ('paypal_receipt_url', models.URLField()),
                ('payment_method_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.payment_methods')),
            ],
        ),
    ]
