# Generated by Django 5.1.2 on 2024-11-13 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='form',
            name='identification_image_url',
            field=models.URLField(null=True),
        ),
    ]
