# Generated by Django 5.1.2 on 2024-11-15 20:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_form_identification_image_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='form',
            name='address_fk',
        ),
        migrations.RemoveField(
            model_name='student',
            name='student_address_fk',
        ),
        migrations.RemoveField(
            model_name='administrator',
            name='admin_address_fk',
        ),
        migrations.AddField(
            model_name='form',
            name='address',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='form',
            name='neighborhood_fk',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.neighborhoods'),
        ),
        migrations.AddField(
            model_name='student',
            name='address',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='neighborhood_fk',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.neighborhoods'),
        ),
        migrations.DeleteModel(
            name='Addresses',
        ),
    ]
