# Generated by Django 5.1.2 on 2024-11-18 20:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_remove_form_address_fk_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='form_fk',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.form'),
        ),
    ]
