# Generated by Django 5.1.2 on 2024-11-19 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0021_alter_payment_payment_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseModality',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modality_name', models.CharField(max_length=50)),
            ],
        ),
    ]
