# Generated by Django 5.1.2 on 2024-11-19 19:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0022_coursemodality'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='enrollment',
            name='enrollment_date',
        ),
        migrations.AddField(
            model_name='enrollment',
            name='course_modality_fk',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.coursemodality'),
        ),
        migrations.AddField(
            model_name='enrollment',
            name='enrollment_end_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='enrollment',
            name='enrollment_start_date',
            field=models.DateTimeField(null=True),
        ),
    ]
