# Generated by Django 5.1.2 on 2024-11-19 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0023_remove_enrollment_enrollment_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='enrollment',
            name='course_status_fk',
        ),
        migrations.AddField(
            model_name='enrollment',
            name='available_spots',
            field=models.IntegerField(null=True),
        ),
    ]
