# Generated by Django 5.1.2 on 2024-11-19 20:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0024_remove_enrollment_course_status_fk_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Course_Status',
        ),
    ]
