# Generated by Django 5.1.2 on 2024-11-19 20:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0025_delete_course_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='enrollment',
            name='student_fk',
        ),
    ]
