# Generated by Django 5.1.2 on 2024-11-19 21:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0026_remove_enrollment_student_fk'),
    ]

    operations = [
        migrations.AddField(
            model_name='form',
            name='payment_fk',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.payment'),
        ),
    ]
