# Generated by Django 5.1.2 on 2024-11-20 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0027_form_payment_fk'),
    ]

    operations = [
        migrations.AddField(
            model_name='courses',
            name='is_free',
            field=models.BooleanField(null=True),
        ),
    ]
