# Generated by Django 5.1.2 on 2024-11-26 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0028_courses_is_free'),
    ]

    operations = [
        migrations.AddField(
            model_name='courses',
            name='course_obligatory_requirements',
            field=models.TextField(null=True),
        ),
    ]
