# Generated by Django 5.1.2 on 2024-12-03 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0033_courses_payment_modality_fk'),
    ]

    operations = [
        migrations.AddField(
            model_name='courses',
            name='obligatory_requirements',
            field=models.TextField(null=True),
        ),
    ]
