# Generated by Django 5.1.2 on 2024-12-05 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0035_alter_payment_payment_receipt_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='payment_receipt_number',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
