# Generated by Django 5.1.2 on 2024-12-10 16:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0038_alter_payment_payment_receipt_number_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student_Courses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.courses')),
                ('student_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.student')),
            ],
        ),
    ]
