# Generated by Django 5.1.2 on 2024-12-12 15:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0039_student_courses'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='genre_fk',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.genre'),
        ),
        migrations.AddField(
            model_name='student',
            name='identification_fk',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.identifications'),
        ),
        migrations.AddField(
            model_name='student',
            name='identification_number',
            field=models.CharField(max_length=50, null=True, unique=True),
        ),
        migrations.CreateModel(
            name='Student_Payments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.payment')),
                ('student_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.student')),
            ],
        ),
    ]
