# Generated by Django 5.1.2 on 2024-12-17 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0041_event'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('creator', models.CharField(max_length=50)),
                ('introduction', models.CharField(max_length=255)),
                ('content', models.TextField()),
                ('image_url', models.URLField(max_length=255)),
                ('likes_count', models.IntegerField(default=0)),
            ],
        ),
    ]
